name: Build OgeeLinux ISO

on:
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: Prepare pacman keyring
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring
      
      - name: Install ArchISO
        run: |
          pacman -Sy
          pacman --noconfirm -S git archiso
      - name: Build ISO File
        run: |
          mkarchiso -v . -w .
          find out/
      - uses: actions/upload-artifact@v2
        with:
          name: OgeeLinuxISO
          path: out/*.iso
      - name: Create Release 
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: auto_release
          name: Automatic Release
          body: Automatic release with github actions
          token: ${{ secrets.GITHUB_TOKEN }}
          files: out/*.iso